<a href="https://colab.research.google.com/github/Nourelhouda1996/DataScience-1/blob/main/Distance_and_time_Starter_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Starter Code

# Exploring NumPy Arrays: Distance and Time

1) Import the numpy library

In [ ]:
import numpy as np

2) Create a numpy array called "distance" that includes the following distances (in meters): 100, 200, 400, 800, 1500, 3000, 5000, 10000

In [2]:
import numpy as np

meters=[100, 200, 400, 800, 1500, 3000, 5000, 10000]
meters_Distance=np.array(meters)

print(meters_Distance)

[  100   200   400   800  1500  3000  5000 10000]


3) Use the np.min() and np.max() functions to find the minimum and maximum distances

In [5]:
import numpy as np

Max_Distance=np.max(meters_Distance)
Min_Distance=np.min(meters_Distance)
print(Max_Distance)
print(Min_Distance)


10000
100


4) To find the average distance, use the np.mean() function

In [6]:
import numpy as np
Average_Distance=np.mean(meters_Distance)
print(Average_Distance)


2625.0


5) use the np.sum() function to find the total distance

In [7]:
import numpy as np
Sum_Distance=np.sum(meters_Distance)
print(Sum_Distance)

21000


6) Another valuable function is the np.cumsum() function which outputs the cumulative sum...notice the output will be 100, 300, 700 as it adds each new distance

In [8]:
import numpy as np
Cumul_Distance=np.cumsum(meters_Distance)
print(Cumul_Distance)

[  100   300   700  1500  3000  6000 11000 21000]


7) To round all of the values in an array, use np.round()

In [9]:
import numpy as np
Values_Distance=np.round(meters_Distance)
print(Values_Distance)

[  100   200   400   800  1500  3000  5000 10000]


8) Create a numpy array called time that includes the following times (in seconds):  10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45

In [11]:
import numpy as np

Seconds=[10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45]
Seconds_Time=np.array(Seconds)

print(Seconds_Time)

[  10.62   21.34   48.25  113.43  233.96  506.53  866.17 1757.45]


9) the values in your time array correspond to olympic records for running the corresponding distances.  Perform the calculation needed to find the speed (in m/s) for each record distance.  Note that speed is distance divided by time.

In [14]:
import numpy as np
Speed_Olym=meters_Distance/Seconds_Time
print(Speed_Olym)



[9.41619586 9.37207123 8.29015544 7.0528079  6.41135237 5.92265019
 5.77253888 5.69006231]


10) One common problem data scientists run into is that we are given information in units that are not consistent.  
For example, we might want to compare data that is given in meters to second to data that is given in miles per hour. A cheetah is the fastest land animal which can reach speeds of 75.0 miles per hour.  
In order to compare our olympians to a cheetah, we need to be able to convert from one unit to another.
Perform calculations to convert the olympic record speeds from meters/second into miles per hour.  Note: 1 meter = 0.00062 miles

How do our olympians compare to the cheetah?

(Hint: Speed in m/s multiplied by 0.00062 and multiplied by 3600 will give speed in miles per hour)

In [17]:
import numpy as np
Speed_Olym=meters_Distance/Seconds_Time
Speed_firstcom=Speed_Olym*0.00062*3600
print(Speed_firstcom)
Max_speed=np.max(Speed_firstcom)
print(Max_speed)



[21.01694915 20.91846298 18.50362694 15.74186723 14.31013849 13.21935522
 12.88430678 12.70021907]
21.016949152542374
